default:
  tags:
    - arm64

pages:
  image: node:20
  script:
    - corepack enable
    - pnpm i
    - pnpm build
    - pnpm build-storybook
  artifacts:
    paths:
      - 'storybook-static'
  publish: storybook-static
