default:
  tags:
    - arm64

publish:
  image: node:20
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
  - corepack enable
  - echo "//git.adofai.gg/api/v4/projects/9/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  - pnpm i
  - NPM_TOKEN=$GL_TOKEN pnpm semantic-release

pages:
  image: node:20
  script:
    - corepack enable
    - pnpm i
    - pnpm build
    - pnpm build-storybook
  artifacts:
    paths:
      - 'storybook-static'
  publish: storybook-static
